---
title: "What Do the Ramones Want?"
output: html_notebook
---

```{r}
#devtools::install_github("dmi3kno/polite")
library(tidyverse)
library(tidytext)
library(rvest)
library(polite)
library(reshape2)
library(wordcloud)

```

Get names of all Ramones songs from azlyrics.com.  Use the `polite` package so we obey the robots.txt instructions at the site.
```{r}
if (file.exists("data/ramones_song_list.rdata")){
  load("data/ramones_song_list.rdata")
} else {
# be polite. get scraping parameters.
base_url <- "https://azlyrics.com"
 song_list_raw <- polite::bow("https://azlyrics.com/r/ramones.html") %>% 
   polite::scrape() %>%
   rvest::html_nodes("#listAlbum a")

song_list <- song_list_raw %>% 
  rvest::html_attr("href") %>% 
  tibble::enframe(name = NULL,value = "lyric_url") %>% 
  dplyr::mutate(song_name = html_text(song_list_raw)) %>% 
  mutate(lyric_url=str_replace(lyric_url,"..",base_url))
save(song_list,file="data/ramones_song_list.rdata")
}

song_list
```

Now get all the lyrics.
```{r}
#make a function to get lyrics

get_lyric <- function(lyric_url){
  lyric <- bow(lyric_url) %>% 
    scrape() %>% 
    #    /html/body/div[4]/div/div[2]/div[5]
    # body > div.container.main-page > div > div.col-xs-12.col-lg-8.text-center > div:nth-child(8)
    html_nodes("div") %>%
    #not happy with this.  relies on the lyrics always being the 22nd `<div>` tag on the page.
    .[22] %>% 
    html_text() %>%
    str_remove_all("\r") %>% 
    str_replace_all("\n"," ") %>% 
    str_trim()
  return(lyric)
}

if (file.exists("data/raw_ramones_lyrics.rdata")){
  load("data/all_ramones_lyrics.rdata")
} else {
  all_lyrics <- NULL
  all_urls <- song_list$lyric_url
  for (lyric_url in all_urls){
    lyric <- get_lyric(lyric_url)
    all_lyrics <- c(all_lyrics,lyric)
    
  }
  save(all_lyrics,file="data/raw_ramones_lyrics.rdata")
}

print(all_lyrics[1])
```

Make into a complete data frame with all the trimmings
```{r}
ramones_lyrics <- song_list %>%  
  bind_cols(enframe(all_lyrics,name="corpus_order",value="lyrics")) %>% 
  mutate(band="Ramones") %>% 
  select(band,song_name,lyrics,lyric_url)

ramones_lyrics
```

```{r}
lyric_words <- ramones_lyrics %>% select(-band,-lyric_url) %>% unnest_tokens(word,lyrics)

```

```{r}
lyric_words_cleaned <- lyric_words %>% anti_join(get_stopwords())

#quick sentiment analysis
positive <- get_sentiments("bing") %>%
  filter(sentiment == "positive")

negative <- get_sentiments("bing") %>%
  filter(sentiment == "negative")

lyric_words_cleaned %>%
  semi_join(positive,by="word") %>%
  group_by(song_name) %>% 
  count(word) %>% 
  group_by(song_name) %>% 
  tally(sort = TRUE,name="Happy Words")
  
```

```{r}
lyric_words_cleaned %>%
  semi_join(negative,by="word") %>%
  group_by(song_name) %>% 
  count(word) %>% 
  group_by(song_name) %>% 
  tally(sort = TRUE,name="Sad Words")
  

```

```{r}
lyric_words_cleaned %>%
  inner_join(get_sentiments("bing"),by="word") %>%
  group_by(song_name) %>% 
  count(sentiment,sort=TRUE) %>% 
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  group_by(song_name) %>% 
  summarise(net_sentiment=sum(n)) %>% 
  filter(abs(net_sentiment) > 10) %>%
  mutate(song_name = reorder(song_name, net_sentiment)) %>%
  mutate(sentiment=ifelse(net_sentiment<0,"Negative","Positive")) %>% 
  ggplot(aes(song_name, net_sentiment, fill = sentiment)) +
  geom_col() +
  coord_flip() +
  labs(title="How Happy are Ramones Songs?",
       y = "Balance of Postive to Negative Words",
       x= "")
```

What is overall sentiment?
Filter out "punk" since this word is not a negative Ramones songs.
```{r}
lyric_words_cleaned %>%
  filter(word != "punk") %>% 
  inner_join(get_sentiments("bing"),by="word") %>%
  count(sentiment,sort=TRUE) %>% 
  ggplot(aes(sentiment, n, fill = sentiment)) +
  geom_col() +
  labs(title="How Happy are the Ramones?",
       y = "Word Count (excluding 'Punk')",
       x= "")

```
```{r}

lyric_words_cleaned %>%
  inner_join(get_sentiments("bing"),by="word") %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("#F8766D", "#00BFC4"),
                   max.words = 100)
```

